# Generated by Django 2.2.17 on 2021-07-31 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IBought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dates', models.ManyToManyField(db_column='dates', default='0', max_length=330, related_name='IBought', to='api.Date')),
                ('task', models.ForeignKey(db_column='task', default='0', max_length=330, on_delete=django.db.models.deletion.CASCADE, related_name='IBought', to='api.Task')),
                ('user', models.ForeignKey(db_column='user', default='0', max_length=330, on_delete=django.db.models.deletion.CASCADE, related_name='IBought', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
