# Generated by Django 2.2.17 on 2021-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_date_ibought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ibought',
            name='dates',
        ),
        migrations.AddField(
            model_name='ibought',
            name='dates',
            field=models.CharField(default='[]', max_length=200),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
