# Generated by Django 2.2.17 on 2021-07-31 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210731_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task', models.ForeignKey(db_column='task', default='0', max_length=330, on_delete=django.db.models.deletion.CASCADE, related_name='WeNeed', to='api.Task')),
                ('user', models.ForeignKey(db_column='user', default='0', max_length=330, on_delete=django.db.models.deletion.CASCADE, related_name='WeNeed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
