# Generated by Django 2.2.17 on 2021-07-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_helper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Helper',
            new_name='History',
        ),
    ]
